'''
L=[('Country',['Sweden','ARN-Stockholm-Arlanda-ARN)',
              '(UME-Umeå-UME)',
              '(LLA-Luleå-LLA)',
              '(KSD-Karlstad-KSD)',
              '(CPH-Köpenhamn-CPH)',
              '(HEL-Helsingfors-HEL)',
              '(KRN-Kiruna-KRN)',
              '(OSL-Oslo-Gardermoen-OSL)',
              '(MMX-Malmö-MMX)',
              'GOT-Göteborg-Landvetter-GOT']),
              ('Country',['Bosnien-Hercegovinia',
              '(SJJ-Sarajevo-SJJ)']),
              ('Country',['Bulgarien',
              '(BOJ-Burgas-BOJ)',
              '(VAR-Varna-VAR)']),
              ('Country',['Cypern',
              '(LCA-Cypern-Larnaca-LCA)']),
              ('Country',['Danmark',
              '(BLL-Billund-BLL)',
              '(CPH-Köpenhamn-CPH)',
              '(AAL-Ålborg-AAL)']),
              ('Country',['Estland',
              '(TLL-Tallinn-TLL)']),
              ('Country',['Finland',
              '(HEL-Helsingfors-HEL)',
              '(IVL-Ivalo-IVL)',
              '(KTT-Kittilä-KTT)',
              '(RVN-Rovaniemi-RVN)',
              '(OUL-Uleåborg-OUL)',
              '(VAA-Vasa-VAA']),
              ('Country',['Frankrike',
              '(BOD-Bordeaux-BOD)',
              '(GNB-Grenoble-GNB)',
              '(AJA-Korsika-Ajaccio-AJA)',
              '(BIA-Korsika-Bastia-BIA)',
              '(MRS-Marseille-Provence-MRS)',
              '(MPL-Montpellier-MPL)',
              '(NCE-Nice-NCE)',
              '(PARALL-Paris-All airports-PARALL)',
              '(CDG-Paris-Charles De Gaulle-CDG)',
              '(ORY-Paris-Orly-ORY)']),
              ('Country',['Förenade Arabemiraten',
              '(DXB-Dubai-DXB)']),
              ('Country',['Grekland',
              '(ATH-Aten-ATH)',
              '(EFL-Kefalonia-EFL)',
              '(CFU-Korfu-CFU)',
              '(KGS-Kos-KGS)',
              '(CHQ-Kreta-Chania-CHQ)',
              '(HER-Kreta-Heraklion-HER)',
              '(PVK-Lefkas Preveza-PVK)',
              '(RHO-Rhodos-RHO)',
              '(JTR-Santorini-JTR)']),
              ('Country',['Guadeloupe',
              '(PTP-Guadeloupe - Pointe-à-Pitre-PTP)']),
              ('Country',['Irland',
              '(DUB-Dublin-DUB)']),
              ('Country',['Island',
              '(KEF-Reykjavik-KEF)']),
              ('Country',['Israel',
              '(TLV-Tel Aviv-TLV)']),
              ('Country',['Italien',
              '(MXP-Milano-MXP)',
              '(PSA-Pisa-Toscana-PSA)',
              '(FCO-Rom-Fiumicino-FCO)',
              '(OLB-Sardinien-Olbia-OLB)',
              '(CTA-Sicilien-Catania-CTA)',
              '(PMO-Sicilien-Palermo-PMO)',
              '(VCE-Venedig-VCE)']),
              ('Country',['Karibien',
              '(PTP-Guadeloupe - Pointe-à-Pitre-PTP)',
              '(FDF-Martinique - Fort-de-France-FDF)',
              '(SJU-Puerto Rico - San Juan-SJU)',
              '(STX-St Croix-STX)']),
              ('Country',['Kosovo',
              '(PRN-Pristina-PRN)']),
              ('Country',['Kroatien',
              '(DBV-Dubrovnik-DBV)',
              '(PUY-Pula-PUY)',
              '(RJK-Rijeka-RJK)',
              '(SPU-Split-SPU)',
              '(ZAG-Zagreb-ZAG)']),
              ('Country',['Lettland',
              '(RIX-Riga-RIX)']),
              ('Country',['Litauen',
              '(PLQ-Palanga/Klaipeda-PLQ)',
              '(VNO-Vilnius-VNO)']),
              ('Country',['Malta',
              '(MLA-Malta-MLA)']),
              ('Country',['Marocko',
              '(AGA-Agadir-AGA)',
              '(RAK-Marrakech-RAK)']),
              ('Country',['Martinique',
              '(FDF-Martinique - Fort-de-France-FDF)']),
              ('Country',['Montenegro',
              '(TIV-Montenegro-Tivat-TIV)']),
              ('Country',['Nederländerna',
              '(AMS-Amsterdam-AMS)']),
              ('Country',['Norge',
              '(ALF-Alta-ALF)',
              '(ANX-Andenes-ANX)',
              '(BDU-Bardufoss-BDU)',
              '(BGO-Bergen-BGO)',
              '(BOO-Bodö-BOO)',
              '(EVE-Harstad/Narvik-EVE)',
              '(HAU-Haugesund-HAU)',
              '(KKN-Kirkenes-KKN)',
              '(KRS-Kristiansand-KRS)',
              '(LKL-Lakselv-LKL)',
              '(MOL-Molde-MOL)',
              '(OSLALL-Oslo-All airports-OSLALL)',
              '(OSL-Oslo-Gardermoen-OSL)',
              '(RYG-Oslo-Rygge-RYG)',
              '(TRF-Oslo-Sandefjord/Torp-TRF)',
              '(SVG-Stavanger-SVG)',
              '(TOS-Tromsö-TOS)',
              '(TRD-Trondheim-TRD)',
              '(AES-Ålesund-AES)']),
              ('Country',['Norge-Svalbard',
              '(LYR-Longyearbyen-Svalbard-LYR)']),
              ('Country',['Polen',
              '(GDN-Gdansk-GDN)',
              '(KRK-Krakow-KRK)',
              '(SZZ-Szczecin-SZZ)',
              '(WAW-Warszawa-WAW)']),
              ('Country',['Portugal',
              '(FAO-Algarve-Faro-FAO)',
              '(LIS-Lissabon-LIS)',
              '(FNC-Madeira-FNC)']),
              ('Country',['Schweiz',
              '(GVA-Genève-GVA)']),
              ('Country',['Serbien',
              '(BEG-Belgrad-BEG)']),
              ('Country',['Spanien',
              '(ALC-Alicante-ALC)',
              '(ALCALL-Alicante-All airports-ALCALL)',
              '(BCN-Barcelona-BCN)',
              '(BIO-Bilbao-BIO)',
              '(FUE-Fuerteventura-FUE)',
              '(LPA-Gran Canaria-LPA)',
              '(IBZ-Ibiza-IBZ)',
              '(ACE-Lanzarote-ACE)',
               '(MAD-Madrid-MAD)',
              '(AGP-Malaga-AGP)',
              '(PMI-Mallorca-Palma-PMI)',
              '(MJV-Murcia-Alicante-MJV)',
              '(TCIALL-Tenerife-All airports-TCIALL)',
              '(TFN-Tenerife-Norte-TFN)',
              '(TFS-Teneriffa-Søder-TFS)']),
              ('Country',['Storbritannien',
              '(BHX-Birmingham-BHX)',
              '(EDI-Edinburgh-EDI)',
              '(LGW-London-Gatwick-LGW)',
              '(MAN-Manchester-MAN)']),
              ('Country',['Sverige',
              '(GOT-Göteborg-Landvetter-GOT)',
              '(KSD-Karlstad-KSD)',
              '(KRN-Kiruna-KRN)',
              '(LLA-Luleå-LLA)',
              '(MMX-Malmö-MMX)',
              '(ARN-Stockholm-Arlanda-ARN)',
              '(UME-Umeå-UME)',
              '(VBY-Visby-Gotland-VBY)']),
              ('Country',['Thailand',
              '(BKK-Bangkok-BKK)']),
              ('Country',['Tjeckien',
              '(PRG-Prag-PRG)']),
              ('Country',['Turkiet',
              '(AYT-Antalya-AYT)']),
              ('Country',['Tyskland',
              '(SXF-Berlin-Schönefeld-SXF)',
              '(HAM-Hamburg-HAM)',
              '(CGN-Köln/Bonn-CGN)',
              '(MUC-München-MUC)']),
              ('Country',['Ungern',
              '(BUD-Budapest-BUD)']),
              ('Country',['USA',
              '(BWI-Baltimore/Washington-BWI)',
              '(BOS-Boston-BOS)',
              '(FLLALL-Florida-Alla flygplatser-FLLALL)',
              '(FLL-Florida-Fort Lauderdale/Miami-FLL)',
              '(MCO-Florida-Orlando-MCO)',
              '(LAS-Las Vegas-LAS)',
              '(LAX-Los Angeles-LAX)',
              '(NYCALL-New York-All airports-NYCALL)',
              '(JFK-New York-John F Kennedy-JFK)',
              '(EWR-New York-Newark Liberty Intl-EWR)',
              '(OAK-Oakland - San Francisco-OAK)']),
              ('Country',['Österrike',
              '(SZG-Salzburg-SZG)',
              '(VIE-Wien-VIE)'])]

'''
